# Generated by Django 4.2.6 on 2023-10-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('check_in_time_start', models.TimeField()),
                ('check_in_time_finish', models.TimeField()),
                ('check_out_time_start', models.TimeField()),
                ('check_out_time_finish', models.TimeField()),
                ('special_note_title', models.CharField(max_length=100)),
                ('special_note_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='stay_information',
            field=models.TextField(),
        ),
    ]
