# Generated by Django 4.2.6 on 2023-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_information_alter_about_stay_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='city_name',
            new_name='city',
        ),
    ]
