# Generated by Django 4.2.6 on 2023-10-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_rename_city_name_about_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='HotelInCity',
        ),
        migrations.RenameModel(
            old_name='Information',
            new_name='ThingsToKnow',
        ),
    ]
