# Generated by Django 4.2.6 on 2023-10-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_rename_thingstoknow_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.hotelincity'),
            preserve_default=False,
        ),
    ]
