# Generated by Django 4.2.6 on 2023-10-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_information_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='picture',
            new_name='avatar',
        ),
    ]
