# Generated by Django 4.2.6 on 2023-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_rename_picture_country_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='avatar',
            new_name='picture',
        ),
    ]
