# Generated by Django 4.2.6 on 2023-10-23 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_rename_avatar_country_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInCityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_price_per_day', models.IntegerField(null=True)),
                ('room_check_in', models.DateField(default=datetime.datetime.now)),
                ('day', models.IntegerField()),
                ('service_charge', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'HotelInCityCost',
                'verbose_name_plural': 'HotelInCityCosts',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='hotelincity',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterField(
            model_name='hotelincity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
