# Generated by Django 4.2.6 on 2023-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_hotelincitycost_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelincitycost',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
