# Generated by Django 3.2.12 on 2023-10-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_alter_hotelincitycost_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelincitycost',
            name='room_check_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
