# Generated by Django 4.2.6 on 2023-11-10 10:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_alter_hotelincitycost_room_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=('middle', 'center'), default='qonday/images.jpeg', force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[400, 400], upload_to='img/avatars/', verbose_name='Avatar'),
        ),
    ]
