# Generated by Django 4.2.6 on 2023-11-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
