# Generated by Django 3.2.12 on 2023-11-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
