# Generated by Django 4.2.6 on 2023-11-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_caradvantages_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvantages',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
