# Generated by Django 4.2.6 on 2023-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_include_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcost',
            name='car_drop_off',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carcost',
            name='car_pick_up',
            field=models.DateField(),
        ),
    ]
