# Generated by Django 4.2.6 on 2023-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carcost_car_drop_off_alter_carcost_car_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcost',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
