# Generated by Django 3.2.12 on 2023-10-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='things_to_know',
            options={'verbose_name': 'know', 'verbose_name_plural': 'knows'},
        ),
        migrations.AddField(
            model_name='experiences_descriptions',
            name='main',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experience.experiences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencescost',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experience.experiences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='include',
            name='main',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experience.experiences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='things_to_know',
            name='main',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experience.experiences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencescost',
            name='person_price_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
