# Generated by Django 3.2.12 on 2023-10-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20231030_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things_to_know',
            name='descriptions1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='things_to_know',
            name='descriptions2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='things_to_know',
            name='descriptions3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='things_to_know',
            name='descriptions4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
